export const DIET_OPTIONS = [
  'balanced',
  'high-fiber',
  'high-protein',
  'low-carb',
  'low-fat',
  'low-sodium',
];

export const HEALTH_OPTIONS = [
  'alcohol-free',
  'celery-free',
  'crustacean-free',
  'dairy-free',
  'egg-free',
  'fish-free',
  'fodmap-free',
  'gluten-free',
  'immuno-supportive',
  'keto-friendly',
  'kidney-friendly',
  'kosher',
  'low-sugar',
  'lupine-free',
  'Mediterranean',
  'mollusk-free',
  'peanut-free',
  'pescatarian',
  'pork-free',
  'red-meat-free',
  'sesame-free',
  'shellfish-free',
  'soy-free',
  'sugar-conscious',
  'tree-nut-free',
  'vegan',
  'vegetarian',
  'wheat-free',
];

export const CUISINE_OPTIONS = [
  'American',
  'Asian',
  'British',
  'Caribbean',
  'Chinese',
  'French',
  'Indian',
  'Italian',
  'Japanese',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Nordic',
  'South American',
  'South East Asian',
];
